
client: VVsp500_10k

prompt_template: 'Classify the term ''{}'' into one of these categories: {}; only
    give name of the class'

system_msgs:
    classification: Ensure that the generated output aligns with one of the predefined
        categories provided. Avoid generating content that does not belong to any
        of these specified categories.

column_map:
    product_real: true_category

categories: []

model_v000:
    max_tokens: 100
    model_type: gpt-4o-mini-2024-07-18
    temperature: 0.7
    top_p: 1

model_v001:
    data_path: null
    date: '2024-09-21'
    max_tokens: 100
    model_type: gpt-4o-mini-2024-07-18
    temperature: 0.7
    top_p: 1
