
client: sp500_10k

prompt_template: 'Classify the paragraph ''{}'' into one of these categories: {};
    only give name of the class'

system_msgs:
    classification: Ensure that the generated output aligns with one of the predefined
        categories provided. Avoid generating content that does not belong to any
        of these specified categories.

column_map:
    item_1a: item_1a
    item_1b: item_1b
    truth: true_category

categories:
- buy
- sell

model_v000:
    max_tokens: 100
    model_type: gpt-4o-mini-2024-07-18
    temperature: 0.7
    top_p: 1

model_v001:
    data_path: data/sp500_10k/v01/mooncake/data/10ks/10ks_truths.csv
    date: '2024-09-19'
    max_tokens: 100
    model_type: ft:gpt-4o-mini-2024-07-18:personal::A9FWA9lp
    temperature: 0.7
    top_p: 1
